server:
  port: 8080

spring:
  application:
    name: greeting-service

  config:
    # importa opcionalmente do configserver
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: it

# actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

# actuator
  endpoint:
    health:
      show-details: ALWAYS

#greeting-service:
#  greeting: "Ol√°"
#  default-value: "Mundo"
