server:
  port: 8888
#  convencao para usar 8888 para config server
spring:
  application:
    name: spring-cloud-config-server
#  profiles:
#    active:
#      - native
  cloud:
    config:
      server:
        git:

          uri: https://github.com/Gusta-code22/curso-config-server
          search-paths: 'greeting-service*'
#          username: username
#          password: