spring:
  application:
    name: rest-with-spring-boot-and-java-erudio

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    open-in-view: false
logging:
  level:
#    github.io.gusta_code22.rest-with-spring-boot-and-java-erudio: error
    root: warn
