services:
  zipkin-server:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    restart: always
    networks:
      - gustadev-network

  naming-server:
    image: gustadev22/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    restart: always
    depends_on:
      - zipkin-server
    networks:
      - gustadev-network


  api-gateway:
    image: gustadev22/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    restart: always
    depends_on:
      - zipkin-server
      - naming-server
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - gustadev-network


  book-service:
    image: gustadev22/book-service
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3306/book_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USER: docker
      SPRING_DATASOURCE_PASSWORD: admin123

    depends_on:
      - zipkin-server
      - naming-server
      - book-db
      - exchange-db
    ports:
      - 8100:8100
    networks:
      - gustadev-network



  exchange-service:
    image: gustadev22/exchange-service
    restart: always
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://exchange-db:3306/exchange_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - exchange-db
      - zipkin-server
      - naming-server
    ports:
      - 8000:8000
    networks:
      - gustadev-network


  book-db:
    image: mysql:9.3.0
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
    ports:
      - 3310:3306
    restart: always

    networks:
      - gustadev-network

  exchange-db:
    image: mysql:9.3.0
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: exchange_service
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123

    ports:
      - 3308:3306

    networks:
      - gustadev-network


networks:
  gustadev-network:
    name: gustadev-network
    driver: bridge
